adjective=input("Please enter an adjective: ")
noun=input("Please enter a noun: ")
verb=input("Please enter a verb ending with -ed: ")
print("Your MadLib: ")
print("The", adjective, noun, verb, "over the fence.")